### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by rbabayoff** [phoqe/rmuif#442] opened 2020-02-17 13:09 UTC
Hey,

I get the following error in the browser when running `yarn start` for the 1st time after installation:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/user1/repos/mail-app/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/user1/repos/mail-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user1/repos/mail-app/node_modules/express/lib/router/index.js:317:13)
    at /home/user1/repos/mail-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/user1/repos/mail-app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user1/repos/mail-app/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/user1/repos/mail-app/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/user1/repos/mail-app/node_modules/express/lib/router/layer.js:95:5)
```

OS: ubuntu 18.04.1
Browser: Google Chrome, latest

**Comment by phoqe** [comment] 2020-02-17 13:10
@rbabayoff Hello, which installation method did you use? And can you try checking out the `develop` branch and run `yarn install` and `yarn start` again?

**Comment by rbabayoff** [comment] 2020-02-17 13:26
I used:

`yarn create react-app mail-app --template rmuif`

When I clone your repo and run `yarn install` and `yarn start` on the master branch it works.

**Comment by phoqe** [comment] 2020-02-17 13:32
Thank you for replying, I think it has something to do with CRA templates not supporting configs in `package.json`. Will look into it closer, for now I recommend cloning instead.

**Comment by phoqe** [comment] 2020-02-17 16:27
I think I have it under control now, will test later when I get home.

**Comment by phoqe** [comment] 2020-02-17 19:08
@rbabayoff It appears to be fixed now, reopen the issue if you encounter any problems. Thank you.

**Closed by phoqe** 2020-02-17 19:08 UTC
Labels: Priority: Critical, Status: Accepted, Type: Bug

**Comment by omrihaim** [comment] 2020-05-04 08:02
Still happening on clean installation using npx

**Comment by phoqe** [comment] 2020-05-04 08:11
@omrihaim I can't reproduce. What Node version are you using, as well as OS?

**Comment by omrihaim** [comment] 2020-05-04 12:25
@phoqe I am on windows. I have an old version of node (10.20) due to a project I've worked on, I will reinstall node and update here.

**Comment by phoqe** [comment] 2020-05-04 12:27
@omrihaim Is your error related to the `moment` dependency? It appears that there is some trouble associated with that package's locale files. You can fix this by downgrading the package. Read more about this [here](https://github.com/moment/moment/issues/5501).

**Comment by omrihaim** [comment] 2020-05-04 12:50
@phoqe this error isn't related to moment. After reinstalling node and yarn to latest versions, I still got this error:
"error This module isn't specified in a package.json file."
![image](https://user-images.githubusercontent.com/3135094/80967380-f6dc0980-8e1e-11ea-96de-23beab07928b.png)

**Comment by phoqe** [comment] 2020-05-04 12:51
@omrihaim I think you have confused RMUIF with another project, the template name for RMUIF is `cra-template-rmuif` not `cra-template-rmw`.

**Comment by omrihaim** [comment] 2020-05-04 12:52
my bad. deleting my comments.
